# Generated by Django 6.0.3 on 2026-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('amplitude_movel', models.JSONField(default=dict)),
                ('lc_i', models.FloatField(default=0)),
                ('lsc_i', models.FloatField(default=0)),
                ('lic_i', models.FloatField(default=0)),
                ('lc_mr', models.FloatField(default=0)),
                ('lsc_mr', models.FloatField(default=0)),
                ('lic_mr', models.FloatField(default=0)),
                ('am_media', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media_Amplitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('media_geral', models.FloatField(default=0)),
                ('amplitude', models.JSONField(default=dict)),
                ('media_amplitude', models.FloatField(default=0)),
                ('lsc_media', models.FloatField(default=0)),
                ('lsc_amp', models.FloatField(default=0)),
                ('lic_media', models.FloatField(default=0)),
                ('lic_amp', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('lc', models.FloatField(default=0)),
                ('lsc', models.FloatField(default=0)),
                ('lic', models.FloatField(default=0)),
                ('taxa', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('lc', models.FloatField(default=0)),
                ('lic', models.FloatField(default=0)),
                ('lsc', models.FloatField(default=0)),
                ('taxa', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
