# Generated by Django 6.0.3 on 2026-04-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Amplitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_geral', models.FloatField(default=0)),
                ('amplitude', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
    ]
