# Generated by Django 6.0.3 on 2026-05-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imr_cp_imr_cpk_imr_lie_imr_lse_imr_x0_imr_x1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imr',
            name='probabilidade',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='probabilidade',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='p',
            name='probabilidade',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='u',
            name='probabilidade',
            field=models.JSONField(default=dict),
        ),
    ]
