# Generated by Django 6.0.3 on 2026-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_media_amplitude_delete_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_amplitude',
            name='lic',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='lsc',
            field=models.JSONField(default=dict),
        ),
    ]
