# Generated by Django 6.0.3 on 2026-04-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_media_amplitude_lic_media_amplitude_lsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_amplitude',
            name='dp_geral',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='media_amplitude',
            name='lic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='media_amplitude',
            name='lsc',
            field=models.FloatField(default=0),
        ),
    ]
