# Generated by Django 6.0.3 on 2026-04-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_media_amplitude_dp_geral_alter_media_amplitude_lic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_amplitude',
            name='media_amplitude',
            field=models.FloatField(default=0),
        ),
    ]
