# Generated by Django 6.0.3 on 2026-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_media_amplitude_media_amplitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_amplitude',
            name='lic',
        ),
        migrations.RemoveField(
            model_name='media_amplitude',
            name='lsc',
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='lic_amp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='lic_media',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='lsc_amp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='lsc_media',
            field=models.FloatField(default=0),
        ),
    ]
