# Generated by Django 6.0.3 on 2026-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_media_amplitude_lic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('lc', models.JSONField(default=dict)),
                ('amplitude_movel', models.JSONField(default=dict)),
                ('lsc', models.IntegerField(default=0)),
                ('lic', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
