# Generated by Django 6.0.3 on 2026-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imr'),
    ]

    operations = [
        migrations.AddField(
            model_name='imr',
            name='am_media',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imr',
            name='lic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imr',
            name='lsc',
            field=models.FloatField(default=0),
        ),
    ]
