# Generated by Django 6.0.3 on 2026-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_imr_am_media_alter_imr_lic_alter_imr_lsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=0)),
                ('dp', models.JSONField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_geral', models.FloatField(default=0)),
                ('lc', models.FloatField(default=0)),
                ('lsc', models.FloatField(default=0)),
                ('lic', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
