# Generated by Django 6.0.3 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='u',
            name='taxa',
            field=models.JSONField(default=dict),
        ),
    ]
