# Generated by Django 6.0.3 on 2026-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_u_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='p',
            name='taxa',
            field=models.JSONField(default=dict),
        ),
    ]
